### ISSUE TITLE
Nice to have:  RXjs 

### ISSUE THREAD

**Issue by nuno** [mobilehero-archive/nativeloop#10]
Nice to have support for RXjs 
 [http://reactivex.io](http://reactivex.io/)   
 [https://github.com/Reactive-Extensions/RxJS](https://github.com/Reactive-Extensions/RxJS)

**Comment by brentonhouse** [comment]
I haven't used RxJS yet.  Do you have ideas as to how you would like the integration to look like?

**Comment by nuno** [comment]
Not really, Im learning, is very powerful.

[https://egghead.io/lessons/rxjs-rxjs-observables-vs-promises](https://egghead.io/lessons/rxjs-rxjs-observables-vs-promises)

**Comment by hansemannn** [comment]
I know some people from the Slack-Community use this already, but I forget who. Ask! :-)

**Comment by brentonhouse** [comment]
I haven't tried this but I wonder how much functionality you get from it:  https://github.com/yuchi/react-titanium
